In [8]:
import numpy as np

rollouts = np.load('data/canonical/rollouts.npz')
print(rollouts['positions'])
print(rollouts['returns'].mean())

[[106  94  93 ...  70  58  70]
 [106  94 106 ...  42  42  43]
 [106  94  82 ...  32  31  30]
 ...
 [106 118 117 ...  57  56  57]
 [106  94  93 ...  37  37  37]
 [106 106  94 ... 121 121 122]]
-193.78671
